import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';

import { Navbar } from '@/components/layout/navbar';
import { cookies } from 'next/headers';
import { getCart } from '@/lib/shopify';
import { CartProvider } from '@/components/cart/cart-context';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = cookies().get('cartId')?.value;
  //Don't await the fetch call because it will block the UI
  const cart = getCart(cartId);

  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.variable} relative`}>
        <CartProvider cartPromise={cart}>
          <Navbar />
          {children}
        </CartProvider>
        <Toaster
          position="top-center"
          theme="light"
          toastOptions={{ className: 'mt-14 md:mt-8' }}
          richColors
        />
        <footer className="w-full h-[524px] bg-secondary" />
      </body>
    </html>
  );
}
