import type { Metadata } from 'next';
import { Inter, DM_Sans } from 'next/font/google';
import './globals.css';

import { Navbar } from '@/components/layout/navbar';

const inter = Inter({ subsets: ['latin'] });

const sans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sans.variable}`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
